import "./app";
import "./services/WebStorageAdapter";
import "./services/CalService";
import "./services/changeDate";
import "./services/setToken";
import "./services/streamService";
import "./route/boards/boards";
import "./js/trelloCal.config";
import "./js/trelloCal.run";
